name: Teste Fiap

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar Dependências
        run: npm install

      - name: Teste API
        run: npm run test

      - name: Teste BDD
        run: npm run cucumber
